on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Asset Version Check
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Checking Assets Step
        uses: ./ # Uses an action in the root directory
        id: hello
      - name: Get the match output
        run: echo "${{ steps.hello.outputs.match }} \none- ${{ steps.hello.outputs.one }}\ntwo- ${{ steps.hello.outputs.two }}\nthree- ${{ steps.hello.outputs.three }}" && echo "one- ${{ steps.hello.outputs.one }}\ntwo- ${{ steps.hello.outputs.two }}\nthree- ${{ steps.hello.outputs.three }}"
